name: TijaratPro Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  frontend-deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: https://tijaratpro-api-598374253827.asia-south1.run.app

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
